require('dotenv').config()
const express = require('express')
const session = require('./config/session')
const authCheckRoutes = require('./routes/auth-check.routes')
const authRoutes = require('./routes/auth.routes')
const userRoutes = require('./routes/user.routes')
const postRouters = require('./routes/post.routes')
const typeStreetRouters = require('./routes/typeStreet.routes')
const streetRouters = require('./routes/street.routes')
const regionRouters = require('./routes/region.routes')
const typeDocumentRouters = require('./routes/typeDocument.routes')
const typeResursRouters = require('./routes/typeResurs.routes')
const typeDeviceRouters = require('./routes/typeDevice.routes.js')
const documents = require('./routes/document.routes.js')
const flats = require('./routes/flat.routes.js')
const houses = require('./routes/house.routes.js')
const houseServiceManafactures = require('./routes/houseServiceManafacture.routes.js')
const periodDeviceReaders = require('./routes/periodDeviceReader.routes.js')
const regionsRouters = require('./routes/region.routes.js')
const serviceManafactures = require('./routes/serviceManafacture.routes.js')
const deviceModels = require('./routes/deviceModel.routes.js')
const deviceMarks = require('./routes/deviceMark.routes.js')
const userAccounts = require('./routes/userAccount.routes.js')
const receipts = require('./routes/receipts.routes.js')
const accountFulls = require('./routes/accountFull.router')
const accounts = require('./routes/account.router')
const app = express()

app.use(express.json({ limit: '50mb' }))
// app.use(express.urlencoded({ extended: true, limit: '50mb' }))
app.use(session)

app.use('/auth-check', authCheckRoutes)
app.use('/api/auth', authRoutes)
app.use('/api/user', userRoutes)
app.use('/api/post', postRouters)
app.use('/api/typeStreet', typeStreetRouters)
app.use('/api/street', streetRouters)
app.use('/api/region', regionRouters)
app.use('/api/typeDocument', typeDocumentRouters)
app.use('/api/typeResurs', typeResursRouters)
app.use('/api/typeDevice', typeDeviceRouters)
app.use('/api/document', documents)
app.use('/api/flat', flats)
app.use('/api/house', houses)
app.use('/api/houseServiceManafacture', houseServiceManafactures)
app.use('/api/periodDeviceReader', periodDeviceReaders)
app.use('/api/regionsRouter', regionsRouters)
app.use('/api/serviceManafacture', serviceManafactures)
app.use('/api/deviceMark', deviceMarks)
app.use('/api/deviceModel', deviceModels)
app.use('/api/userAccount', userAccounts)
app.use('/api/receipts', receipts)
app.use('/api/accountFulls', accountFulls)
app.use('/api/accounts', accounts)

module.exports = app
